name: flutter_easyloading
description: modified easy loading version
version: 3.0.3
homepage: https://github.com/nslog11/flutter_easyloading

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0
  responsive_framework: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
